name: Create issues from todos

on:
  push:
    branches:
     - master

jobs:
  todos:
    runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v1
        - name: todo-actions
          uses: dtinth/todo-actions@master